# Location selection demo

In [2]:
%matplotlib qt

import numpy as np
import random
import matplotlib.pyplot as plt

plt.ion()

n = 20


In [3]:

def generate_cities(n, seed):
    random.seed(seed)
    # Generate n cities with random coordinates
    cities = [(random.uniform(0, 100), random.uniform(0, 100)) for _ in range(n)]
    return cities

def calculate_distance(city1, city2):
    # Calculate Euclidean distance between two cities
    return np.sqrt((city1[0] - city2[0]) ** 2 + (city1[1] - city2[1]) ** 2)

def create_popuations(n):
    populations = np.array([(random.triangular(-1, 1)**2)*1000 for _ in range(n)]).round() * 100
    return populations


def create_adjacency_matrix(cities):
    n = len(cities)
    adjacency_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i != j:
                adjacency_matrix[i][j] = calculate_distance(cities[i], cities[j])
    
    return adjacency_matrix

def plot_cities(cities, populations):
    # Plot the cities on a Cartesian coordinate system
    x_coords, y_coords = zip(*cities)
    
    plt.figure(figsize=(8, 8))
    plt.scatter(x_coords, y_coords, color='blue', s=populations)
    
    for idx, city in enumerate(cities):
        plt.annotate(f'City {idx}', (city[0], city[1]), textcoords="offset points", xytext=(0,10), ha='center')
    
    plt.title('Cities on Cartesian Coordinate System')
    plt.xlabel('X Coordinate')
    plt.ylabel('Y Coordinate')
    plt.xlim(0, 100)
    plt.ylim(0, 100)
    plt.grid()
    plt.show()


In [4]:

cities = generate_cities(n, 20250424)
adjacency_matrix = create_adjacency_matrix(cities)

populations =  create_popuations(n)

print("Cities (x, y coordinates):")
for idx, city in enumerate(cities):
    print(f"City {idx}: {city}")

display(populations)

marker_downscale_factor = 100

plot_cities(cities, populations/marker_downscale_factor)


Cities (x, y coordinates):
City 0: (32.46821836623819, 65.6367050713251)
City 1: (41.46946457143136, 11.074940883410756)
City 2: (64.68706866275423, 18.29866757939975)
City 3: (56.495641690255404, 59.94933047990521)
City 4: (87.03017457027464, 60.68910745781123)
City 5: (68.80106902642386, 66.61044527267815)
City 6: (92.42222879273424, 9.364236019688455)
City 7: (87.79829165933444, 36.309928388930615)
City 8: (44.10165173236453, 57.51853082264592)
City 9: (14.490232094387734, 72.0503438723459)
City 10: (29.143877429431985, 36.40846376858325)
City 11: (56.381271888862926, 0.432253657464321)
City 12: (75.8037311880652, 26.766295375807147)
City 13: (88.87289700856203, 78.68439171798221)
City 14: (64.82474760435812, 37.59284979203431)
City 15: (25.888051470266383, 17.664498884072366)
City 16: (19.3495636968418, 31.504871048729)
City 17: (29.764644570646837, 67.217846188787)
City 18: (74.84165299950143, 47.80891175884086)
City 19: (38.06185410281583, 96.50075129706605)


array([29600., 40900., 54400.,     0.,  4100.,  2400.,   100.,     0.,
        6200.,   400.,  2600.,   900., 13800.,  8200., 17100.,   400.,
        1600.,   900.,  3400.,   500.])

## Representation of problem

In [5]:
from pymoo.core.problem import Problem
from pymoo.util.ref_dirs import get_reference_directions
from pymoo.optimize import minimize
from pymoo.algorithms.moo.nsga3 import NSGA3

class clinicOptimization(Problem):

    def __init__(self, cities, max_city, city_pops, min_atp, home):
        city_n = len(cities)
        super().__init__(n_var=city_n, n_obj=3, n_ieq_constr=1, xl=0, xu=1, vtype=bool)
        self.max_city = max_city
        self.city_pops = city_pops
        self.min_atp = min_atp
        self.home = home


    def _evaluate(self, x, out, *args, **kwargs):
        x_bool = x < 0.5
        np.multiply(x_bool, self.city_pops)

        visited_per_solution = np.multiply(x_bool, self.city_pops)

        # Objective 1: Maximize total population visited 
        total_pop_visited = visited_per_solution.sum(axis=1)

        # Objective 2: Maximize the total number of cities visited 
        total_cities_visited = x_bool.sum(axis=1)

        # Objective 3: Minimize the total number of events that are overstaffed
        overstaffed_events = np.logical_and(visited_per_solution < self.min_atp, visited_per_solution != 0)
        total_overstaffed_events = overstaffed_events.sum(axis=1)

        # Wrap up our objectives all nice and pretty
        out["F"] = np.column_stack([
            -total_pop_visited,              # max
            -total_cities_visited,           # max
            total_overstaffed_events])       # min

        # Constrains: Total cities visited
        out["G"] = total_cities_visited < self.max_city       




# atp = attendees per site 
# (this is just going off of raw pop, though normally we'd want to estimate the total 
# number of visitors per capital)
min_atp = 1000

home = np.array([50,50])
prob = clinicOptimization(cities, 10, populations, min_atp, home)

ref_dirs = get_reference_directions("das-dennis", 3, n_partitions=12)

algorithm = NSGA3(pop_size=200,
                  ref_dirs=ref_dirs)

res = minimize(prob,
               algorithm,
               ('n_gen', 100),
               verbose=False)

display(res.X < 0.5)
display(res.F)





array([[ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True, False,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

array([[-1.861e+05, -1.600e+01,  2.000e+00],
       [-1.874e+05, -1.900e+01,  5.000e+00],
       [-1.852e+05, -1.500e+01,  1.000e+00],
       [-1.866e+05, -1.700e+01,  3.000e+00],
       [-1.870e+05, -1.800e+01,  4.000e+00],
       [-1.875e+05, -2.000e+01,  6.000e+00],
       [-1.843e+05, -1.400e+01,  0.000e+00]])

In [6]:
import pandas as pd

results = pd.DataFrame(res.F, 
                       columns=["Total Population Visited", "Total Cities visited", "Number of over staffed events"])
results.loc[:,"Total Population Visited"] = np.abs(results.loc[:,"Total Population Visited"])
results.loc[:,"Total Cities visited"] = np.abs(results.loc[:,"Total Cities visited"])

results

Total Population Visited  Total Cities visited  \
0                  186100.0                  16.0   
1                  187400.0                  19.0   
2                  185200.0                  15.0   
3                  186600.0                  17.0   
4                  187000.0                  18.0   
5                  187500.0                  20.0   
6                  184300.0                  14.0   

   Number of over staffed events  
0                            2.0  
1                            5.0  
2                            1.0  
3                            3.0  
4                            4.0  
5                            6.0  
6                            0.0

In [7]:
from mpl_toolkits.mplot3d import Axes3D

x = results.loc[:,"Total Population Visited"]
y = results.loc[:,"Total Cities visited"]
z = results.loc[:,"Number of over staffed events"]

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(x, y, z,
           linewidths=1, alpha=.7,
           edgecolor='k',
           s = 200,
           c=z)

ax.set_xlabel("Total population visited")
ax.set_ylabel("Total cities visited")
ax.set_zlabel("Number of overstaffed events")

plt.show()

In [ ]:
#import numpy as np
#from mpl_toolkits.mplot3d import Axes3D
#
## Generate random data for the scatter plot
#num_points = 100
#x = results.loc[:,"Total Population Visited"]
#y = results.loc[:,"Total Cities visited"]
#z = results.loc[:,"Number of over staffed events"]
#
## Create a 2x2 figure
#fig = plt.figure(figsize=(10, 10))
#
## Define the viewing angles for each subplot
#view_angles = [(30, 30), (30, -30), (30, -60), (30, -180)]
#
## Create subplots
#for i in range(2):
#    for j in range(2):
#        ax = fig.add_subplot(2, 2, i * 2 + j + 1, projection='3d')
#        ax.scatter(x, y, z, c = z)
#        ax.set_title(f'View angle: {view_angles[i * 2 + j]}')
#        ax.view_init(elev=view_angles[i * 2 + j][0], azim=view_angles[i * 2 + j][1])
#
## Adjust layout
#plt.tight_layout()
#plt.show()